[package]
name = "json-data-cache"
resolver = "2"
edition = "2024"
version = "0.1.0"

[dependencies]
regex = "1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1", features = ["preserve_order"] }
aho-corasick = { version = "1.1.4" }
